
title: Khusamov Sukhrob

email: khusamov@yandex.ru

description: >
  Мои заметки по программированию.

baseurl: ""

url: "http://khusamov.github.io/"

github_username:  khusamov

markdown: markdown-it

theme: jekyll-theme-merlot
