// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
	solidSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

module.exports = sidebars;
