// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
module.exports = {
	tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
	solidSidebar: [{ type: 'autogenerated', dirName: '.' }]
};
