name: Docusaurus Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Позволяет запустить этот рабочий процесс вручную на вкладке Действия
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: yarn -v

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
