name: Публикация сайта Docusaurus на GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Позволяет запустить этот рабочий процесс вручную на вкладке Действия
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Установить последнюю версию Yarn
        run: | 
          yarn set version stable
          yarn -v

      - name: Установить все зависимости проекта
        run: yarn install

      - name: Опубликовать сайт на GitHub Pages
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
