name: GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#       - name: Git Setup
#         run: |
#           git config user.name Khusamov Sukhrob
#           git config user.email khusamov@yandex.ru
      
      - name: Переменные окружения для Docusaurus
        run: |
          export GIT_USER=khusamov
          export USE_SSH=true
      
      - name: Установить последнюю версию Yarn
        run: | 
          yarn set version stable
          yarn -v

      - name: Установить все зависимости проекта
        run: yarn install

      - name: Опубликовать сайт на GitHub Pages
        run: yarn deploy
