name: GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_USER: khusamov
#       USE_SSH: true
    steps:
      - uses: actions/checkout@v3
      
      - name: Git Setup
        run: |
          git config --global user.name "Khusamov Sukhrob"
          git config --global user.email "khusamov@yandex.ru"
          git remote set-url --push origin https://khusamov:${{secrets.TOKEN}}@github.com/khusamov/khusamov.github.io.git
            
      - name: Установить последнюю версию Yarn
        run: | 
          yarn set version stable
          yarn -v

      - name: Установить все зависимости проекта
        run: yarn install

      - name: Опубликовать сайт на GitHub Pages
        run: yarn deploy
