name: GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Установить последнюю версию Yarn
        run: | 
          yarn set version stable
          yarn -v

      - name: Установить все зависимости проекта
        run: yarn install

      - name: Опубликовать сайт на GitHub Pages
        run: yarn deploy
